spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost3306/customer-master
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false  
